// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeSpend.Web.Services.Plaid;

#nullable disable

namespace SafeSpend.Web.Data.Migrations.SafeSpend
{
    [DbContext(typeof(SafeSpendDbContext))]
    partial class SafeSpendDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SafeSpend.Web.Services.Plaid.BillScheduleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("NextDueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BillSchedules");
                });

            modelBuilder.Entity("SafeSpend.Web.Services.Plaid.PaycheckScheduleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CushionCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FollowingPaycheckDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("NextPaycheckDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PaycheckSchedules");
                });

            modelBuilder.Entity("SafeSpend.Web.Services.Plaid.PlaidConnectionEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastWebhookAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastWebhookCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedAccessToken")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionCursor")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("PlaidConnections");
                });

            modelBuilder.Entity("SafeSpend.Web.Services.Plaid.PlaidItemEntity", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionCursor")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("PlaidItems");
                });

            modelBuilder.Entity("SafeSpend.Web.Services.Plaid.PlaidTransactionEntity", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalFinanceDetailedCategory")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalFinancePrimaryCategory")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "TransactionId");

                    b.ToTable("PlaidTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
